name: Run Kubernetes Commands

on:
  push:
    branches:
      - main

jobs:
  run-kubectl-commands:
    runs-on: self-hosted  # This will use your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a batch script
        run: |
          echo Running commands on Windows VM
          dir
          echo Script finished
